version: '3'
services:
    proxy:
        image: virtualzone/jwt-auth-proxy
        restart: unless-stopped
        ports:
            - 8080:8080
        networks:
            - app
            - db
            - frontend
        volumes:
            - /opt/docker/jwt-auth-proxy/certs:/app/certs
        environment:
            MONGO_DB_URL: 'mongodb://mongo:27017'
            PROXY_TARGET: 'http://app:80'
        depends_on:
            - mongo
    mongo:
        image: mongo:4
        restart: unless-stopped
        networks:
            - db
        volumes:
            - /opt/docker/jwt-auth-proxy/db:/data/db
    app:
        image: nginx
        restart: unless-stopped
        networks:
            - app
networks:
    db:
    app:
    frontend:
        driver: bridge